@isTest(SeeAllData=True)
public class Test_NcaTriggers{

    public static testMethod void doIt(){
        /*Contact c = new Contact(FirstName='Chris', LastName ='Vitone', Email='Cvitone@gmail.com');
        insert c;
        
        Rebate__c r = new Rebate__c();
        r.FormCode__c = 'SGERF2012';
        r.RebateStatus__c = 'Non-Compliant';
        r.Name = 'TEST';
        r.ContactID__c = c.id;
        insert r;
        
        r = [select id, formId__c from Rebate__c where id =: r.id];
        System.assert(r.formId__c != null, 'Null Bitch');
        
        NCA__c n = new NCA__c(Name='TestNCA', PdxId__c = 'TEST');
        insert n;
        
        r.ncaId__c = n.id;
        update r;
        
        NcaLetter__c l = new NcaLetter__c(ncaId__c = n.id, letter__c = 'Letter_1', name = 'TEST LETTER 1', HasDetails__c = false, Type__c = 'C', Header__c = 'Header', Footer__c = 'Footer', PdxId__c = 'TEST LETTER 1');
        insert l;
    
        NcaEmailMgr nMgr = new NcaEmailMgr();
        System.assert(nMgr.sendEmail(l.id));
        */
      }
        
    }